### ISSUE TITLE
The Executive Summary needs a major do-over  

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-AIP#3]
At the moment it is too focused on the E-ARK project. It should be a proper executive summary without references to E-ARK.

**Comment by delvej** [comment]
See DLMArchivalStandardsBoard/GroupDocumentation#1 for generic template issue. This will be dealt with after this has been fixed.

**Comment by shsdev** [comment]
I added a short paragraph and named it "DAS Board AIP specification". However, there should be a consistent naming across the different specs. I think we can maintain the reference to the E-ARK specification as this is where this document is based upon.

**Comment by shsdev** [comment]
Currently, the naming I applied in the AIP spec is  naming is DASBOARD AIP and DASBOARD IP for the "Common Specification".

**Comment by kuldaraas** [comment]
Until now the naming has been that the common part is "Common Specification (for Information Packages)" and individual IPs are of "E-ARK brand" (E-ARK SIP, E-ARK AIP, E-ARK DIP). This can all be reviewed and discussed. However, as we already know that we will drop the DAS Board branding then DASBOARD AIP and DASBOARD IP should not be used.

**Comment by shsdev** [comment]
Ok, the document v1.0.2 is updated accordingly. The common specification is named "Common Specification for Information Packages" or short "Common Specification for IPs".
