### ISSUE TITLE
Proposal of adding Retention/Disposal elements: Proposed element Preservation status

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#34]
Proposed element Preservation status. Status for retention, disposal or preservation. S=Save, preserve (swe. bevara), DI=Disposal, retention (swe. gallra), PA=PAused (swe. parkerad), UN=UNknown (swe. okänt). Element type: String. Allowed values: S, DI, PA, UN

**Comment by karinbredenberg** [comment]
Connected to https://github.com/DILCISBoard/E-ARK-CSIP/issues/361

**Comment by shsdev** [comment]
Decided in https://github.com/DILCISBoard/E-ARK-CSIP/issues/361 that this is beyond the scope of a generally applicable specification.
