### ISSUE TITLE
Proposal of adding Retention/Disposal elements: Proposed element Preservation date

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#35]
Proposed element Preservation date. Date after which disposal of AIP shall occur if PreservationStatus="DI". That is preservation shall only occur up to and including this date, i.e. package shall be retained to this date. E.g. ”2020-01-01” means that the AIP shall be destroyed (directly) after this date (or retained to this date depending on ones viewpoint.). Element type: YYYY-MM-DD. Shall be given if PreservationStatus="DI". Otherwise it is optional.

**Comment by karinbredenberg** [comment]
Connected to https://github.com/DILCISBoard/E-ARK-CSIP/issues/362

**Comment by shsdev** [comment]
Decided in [DILCISBoard/E-ARK-CSIP/issues/362](https://github.com/DILCISBoard/E-ARK-CSIP/issues/363) that this is beyond the scope of a generally applicable specification.
