### ISSUE TITLE
Proposal of adding Retention/Disposal elements: Proposed element Preservation reference

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#36]
Proposed element Preservation reference. Law or other regulation that determins preservation, disposal or retention. E.g. "RA-FS 2030:12". Element type: Free text. Min 1 character. Max 255 characters.

**Comment by karinbredenberg** [comment]
connected to https://github.com/DILCISBoard/E-ARK-CSIP/issues/363

**Comment by shsdev** [comment]
Decided in [DILCISBoard/E-ARK-CSIP/issues/363](https://github.com/DILCISBoard/E-ARK-CSIP/issues/363) that this is beyond the scope of a generally applicable specification.
