### ISSUE TITLE
Proposal of adding Information security classification: Proposed element Classification

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#37]
Proposed element Classification. Security classification of information in package. P=Publik (eng. public or declassified), BS=Begränsat Skyddsvärde (eng. restricted), HS=Högt Skyddsvärde (eng. confidential), EJ KLASSAT=Ej Klassat, okänd klassning (eng. unclassified, unknown). Elements type: String. Allowed values: P, BS, HS, EJ KLASSAT. "EJ KLASSAT" is default. Values could be extended to support different organisations requirements.

**Comment by karinbredenberg** [comment]
Connected to https://github.com/DILCISBoard/E-ARK-CSIP/issues/364

**Comment by karinbredenberg** [comment]
Connected to issue https://github.com/DILCISBoard/E-ARK-CSIP/issues/364

**Comment by shsdev** [comment]
Decided in DILCISBoard/E-ARK-CSIP/issues/364 that this is beyond the scope of a generally applicable specification. See related issue https://github.com/DILCISBoard/E-ARK-CSIP/issues/364.
