### ISSUE TITLE
Proposal of adding Keywords (subjects) to make an IP searchable: Proposed element Keywords

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#38]
Proposed element Keywords. A list of keywords used for searching. E.g. "TMJ, BB, varumärkesintrång, värde2variabel" or "TMJ BB varumärkesintrång värde2variabel". Element type: Free text. Max 20 words separated by (space) or (comma). Max 2047 characters.

**Comment by karinbredenberg** [comment]
Connected with https://github.com/DILCISBoard/E-ARK-CSIP/issues/365

**Comment by shsdev** [comment]
Similar to https://github.com/DILCISBoard/E-ARK-CSIP/issues/365 this is beyond the scope of a generally applicable specification. Decision: close issue.
