### ISSUE TITLE
All extra elements for SIP, AIP and DIP should be included in CSIP

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#39]
In Sweden we have not created separate FGSs for SIP, AIP and DIP. We recommend that all extra elements for SIP, AIP and DIP should be included in CSIP, but as optional information. Then, documents are needed that describe how to create a SIP, AIP, DIP and how to use the elements at EU level and that it is possible to adapt for local use in different countries.

**Comment by karinbredenberg** [comment]
Connected to issue https://github.com/DILCISBoard/E-ARK-CSIP/issues/371

**Comment by shsdev** [comment]
https://github.com/DILCISBoard/E-ARK-CSIP/issues/371
