### ISSUE TITLE
Documents for the different IPs should be standardized

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-AIP#40]
The documents for the different IPs should be standardized so that they are structured in a similar way and the references should keep the same ID for the same element (CSIP7 should always be the same element in all documents).

**Comment by karinbredenberg** [comment]
Connected to issue https://github.com/DILCISBoard/E-ARK-CSIP/issues/372

**Comment by shsdev** [comment]
This is bein addressed in the CSIP: https://github.com/DILCISBoard/E-ARK-CSIP/issues/372
