### ISSUE TITLE
Uniform use of folder and directory

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-AIP#42]
Words "folder" vs. "directory" should be uniform. Technically, "folder" is different from "directory" (folder may be a physical or a virtual folder, whereas directory is always physical directory in a file system).

**Comment by shsdev** [comment]
Using 'folder' and directory. So I would change all to 'folder'.

**Comment by shsdev** [comment]
https://github.com/DILCISBoard/E-ARK-AIP/commit/f6843b706cf1172fe114b15c436dd5ff74afba29
