### ISSUE TITLE
Duplication of images in the specification

### ISSUE THREAD

**Issue by elbre** [DILCISBoard/E-ARK-AIP#74]
Good day!

I noticed that the specification published at https://earkaip.dilcis.eu/ contains the same image describing two different cases of versioning packages.

6.5. Appendix E - Naming scheme examples
Image figure 9 and image figure 10 have the identical source 
"https://earkaip.dilcis.eu/figs/ditaa/ditaa_appendix_e_migration_segmented.png"

**Comment by shsdev** [comment]
Thank you! We corrected this in pull request https://github.com/DILCISBoard/E-ARK-AIP/pull/78 which goes into the release v2.1.1 of the specification.
